	stage('Test'){
   	  steps {
	   script {
	     sh 'echo "Test Stage"'
}
}
}

	stage('Package'){
   	  steps {
	    script {
	      sh 'echo "Package Stage"'
}
}
}

	stage('Deploy'){
	  steps {
	    script {
	      sh 'echo "Deploy Stage"'
}
}
}

	stage('Cleanup'){
    	  steps {
	    script {
	      sh 'echo "Clean-up Stage"'
}
}
}

}


}
